### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by zinuznet** [spencermountain/dumpster-dive#104]
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/dumpster-dive/node_modules/chalk/source/index.js from /usr/local/lib/node_modules/dumpster-dive/src/index.js not supported.
Instead change the require of /usr/local/lib/node_modules/dumpster-dive/node_modules/chalk/source/index.js in /usr/local/lib/node_modules/dumpster-dive/src/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/dumpster-dive/src/index.js:3:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/dumpster-dive/bin/dumpster.js:2:16) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by spencermountain** [comment]
hey @zinuznet we can add a type:"commonjs" property to the package json of this library, which may help.
Otherwise, it may be an issue on chalk. We can remove that lib if it causes trouble. I've never seen this before.
cheers

**Comment by spencermountain** [comment]
ahh, sorry i blindly update this lib last week. i will roll it back now

**Comment by spencermountain** [comment]
fixed in `5.6.2`
