### ISSUE TITLE
How do I filter pages by description?

### ISSUE THREAD

**Issue by rbbt99** [spencermountain/dumpster-dive#114]
Specifically I would like to filter by the short description field:
`{{Short description|1989 video game}}`

**Comment by spencermountain** [comment]
hi @rbbt99 - i would do something like this -
```js
dumpster({
  file: path,
  db: dbName,
  custom: function (doc) {
    let t = doc.template('short description')
    if (t && t.json().description.match(/video game/i)) {
      return doc.json()
    }
    return null
  },
})
```
returning null, if I remember, prevents the page from loading into mongo.
cheers
