### ISSUE TITLE
disambiguation-page parsing

### ISSUE THREAD

**Issue by michaelbailey** [spencermountain/dumpster-dive#18]
Certain disambiguation pages to do not contain all of the expected links.

For example,
https://en.wikipedia.org/wiki/Fly_(disambiguation)

When looking in MongoDb for
`title:"Fly (disambiguation)"`

The type of this document is `page` and it only contains the intro in `text` property. None of the other paragraphs/links have been imported.

**Comment by spencermountain** [comment]
hey thanks michael, which version are you using?
if you plug it into [here](https://spencermountain.github.io/wtf_wikipedia/), it seems to work, are you on an older version?
cheers

**Comment by spencermountain** [comment]
think this works now, lemme know if not
