### ISSUE TITLE
Article count of enwiki

### ISSUE THREAD

**Issue by EdonGashi** [spencermountain/dumpster-dive#19]
Hi, thanks for making this tool. It's not really an issue but I couldn't find an answer anywhere online.

I started processing the 13 gb enwiki using the simple single-threaded approach, thinking that plus minus a few hours wouldn't make that much of a difference... 4 days later it's still going at ~8.4 million records processed.

Does anyone have an estimate on how many items there are? I expected about 5 million so I kept waiting that it would be done in any minute 😆

**Comment by spencermountain** [comment]
wha! that's awesome. yeah, sounds like something is up. Shouldn't go that long!

i say time to start poking around in the mongo console. it is probably my fault, i'm happy to help, if only to reduce your electrical bill ;)

gotta be in a loop somehow. do a `db.find({}).skip(7000000).limit(10)` or something crazy like that? lemme know.

**Comment by EdonGashi** [comment]
```
> db.wikipedia.find({}).skip(7000000).limit(10)
{ "_id" : "Puttalama District", "type" : "redirect", "redirect" : "Puttalam District", "title" : "Puttalama District" }
{ "_id" : "Macrodystrophy lipomatosa", "type" : "redirect", "redirect" : "Hamartoma", "title" : "Macrodystrophy lipomatosa" }
{ "_id" : "Fibrolipomatosis", "type" : "redirect", "redirect" : "Hamartoma", "title" : "Fibrolipomatosis" }
{ "_id" : "Ampāṟai", "type" : "redirect", "redirect" : "Ampara", "title" : "Ampāṟai" }
{ "_id" : "Patuḷai", "type" : "redirect", "redirect" : "Badulla", "title" : "Patuḷai" }
{ "_id" : "Cantharellus lutescens", "type" : "redirect", "redirect" : "Craterellus lutescens", "title" : "Cantharellus lutescens" }
{ "_id" : "Facial deformity", "type" : "redirect", "redirect" : "Deformity", "title" : "Facial deformity" }
{ "_id" : "Ampāntōṭṭai", "type" : "redirect", "redirect" : "Hambantota", "title" : "Ampāntōṭṭai" }
{ "_id" : "Yāl̮ppāṇam", "type" : "redirect", "redirect" : "Jaffna", "title" : "Yāl̮ppāṇam" }
{ "_id" : "Mahanuvara", "type" : "redirect", "redirect" : "Kandy", "title" : "Mahanuvara" }
```

A loop seems unlikely, if IDs are unique then the collection size would be lower, right?

```
> db.wikipedia.count()
8417830
```

When I started it it chewed through hundreds of thousands rather quickly, now it has slowed to a crawl, something like 10-20 inserts per second. May be mongo not being able to handle the size, who knows.

**Comment by spencermountain** [comment]
yeah, exactly. that confuses me too, because if it were looping, it would be over-writing those records. I'm pretty curious now. I've never heard of this happening before.

yeah, it was built not to keep many things i RAM, but if your ram fills up, then it will begin to go very slowly.
... still... why 8 million records?

oh hey, those are all redirects, maybe that's something try:
```
db.wikipedia.count({type:"redirect"})
```
i'm just looking now at how many are supposed to be redirects. my guess is 3/4 a million or so.

**Comment by spencermountain** [comment]
oh hey, i'm totally wrong.
The count on the front page of Wikipedia - 5.5M - does not include redirects, but the dump does, so the total you should expect should be well north of 5.5M... maybe even 8million?...

**Comment by EdonGashi** [comment]
Yeah I noticed the redirects too, but it was a coincidence, since I did something like 7100000 and it returned random pages.

I stopped at ~8.5 million, dropped everything and started over. I modified your code to pluck only the data I need from the pages, which should be less than 20% of the original data size. Now it's going faster, at 6.2 million after ~12 hours.

Again though, after the first few millions it has slowed down, I hope it can pull through the second half in reasonable time. The single threaded node is using 1-2-1.5GB ram in a 8gb machine. If there's a memory leak or something it would likely be the reason of the gradual slow down.

I also saw in the readme that you wrote 51GB db size, mine was around 15GB when I dropped it. If that was only 1/3 of the progress then not a chance it would have finished this year. I fear that it's about 24 million for combined pages+redirects+disambiguations

I tried the redis method and it was quite faster, but I'm on windows and the port kept throwing net exceptions at ~300k.

I'll give the final numbers here when it's finished so that other people can have a reference. Thanks!

**Comment by spencermountain** [comment]
thanks. i appreciate it, and I wish i could do more to help.

**Comment by EdonGashi** [comment]
Out of heap memory exception at 9.7 million ~_~

Any idea if I can seek up to that article and continue parsing from there? I don't have the multistream version though, and I'm not sure where this huge memory usage comes from. It can be the extractor or parser. I'll try to run some experiments

**Comment by spencermountain** [comment]
hey, yeah not sure. You could always add a condition [here](https://github.com/spencermountain/wikipedia-to-mongodb/blob/master/src/index.js#L44) that ignores all the pages with a count below 9 million or something.

or maybe it's an option in [xml-stream](https://github.com/assistunion/xml-stream). Your guess is as good as mine.

**Comment by EdonGashi** [comment]
Did that, then waited a day to get back to the count where it left off, it parsed a few more thousands and crashed again. Something is leaking a lot of memory. I won't bother any further since I'll make do with these articles I have.

To anyone who attempts this, try to up the node heap size before launching the parser. By default it seems to have 1.76 GB.

**Comment by spencermountain** [comment]
getting reports of full end-to-end en-wikipedia in 6h on latest version!
