### ISSUE TITLE
this doesn't work `wp2mongo /path/to/my-wikipedia-article-dump.xml.bz2`

### ISSUE THREAD

**Issue by devrim** [spencermountain/dumpster-dive#27]
hi spencer, thanks for the amazing work though i couldn't get it to work. here what i'm seeing: 

```
wp2mongo ~/Downloads/afwiki-latest-pages-articles-multistream.xml.bz2


 --- starting xml parsing --

=================done!=================
0  pages stored in db 'afwiki'
```
any ideas why?

**Comment by devrim** [comment]
it's strange, on package.json engine is specified as 0.10.33, i downgraded to that, but then code is es6,  it throws "unexpected identifier" error, since it can't execute es6 - if i downgrade, npm install and then upgrade and run the code, then node-expat (part of xml-parser) complains that `bindings not defined` 

i'd really appreciate any pointers..

**Comment by spencermountain** [comment]
hey Devrim, hey sorry bout the delay.
yikes, sounds like a gross versioning problem. Yeah, i think the best-practice for us is still to write es5, and we should just do that, and remove the `engine` field.
I think that may just mean replacing our `const + let` to `vars` ... it may be that simple.

if it's helpful, i use [nvm](https://github.com/creationix/nvm) and just try to remember to `rm -rf ./node_modules && npm install` after I change node versions. Hopefully xml-parser will build on any modern or old node env, but i'm not sure.

**Comment by spencermountain** [comment]
hey devrim, i basically re-wrote all of it. I think it will no-longer have the slowdown/hang issue.
wanna try it out?
https://github.com/spencermountain/wikipedia-to-mongodb/tree/dev
i removed the redis option for now. may try something else later.
lemme know how it goes. I will put it on master if it works for you.
cheers

**Comment by devrim** [comment]
awesome! trying it now.. i will report back.

**Comment by spencermountain** [comment]
the `insertMany` thing is dope. thank you for that.

**Comment by MTKnife** [comment]
When you say it no longer has the hang issue, does that refer to #21?

**Comment by spencermountain** [comment]
hey Scott, yeah, @devrim has completely fixed your problem. It's amazing.
I was planning on telling you once we released it, which I haven't done yet.
you can checkout [the dev branch](https://github.com/spencermountain/wikipedia-to-mongodb/tree/dev) and see how some of the tests are running. The docs aren't up-to-date yet.

if you're curious, the hanging seems to be from the xml-stream package. The two of us were looking in the wrong place.

hope to release it this week. It's behind some new changes in wtf_wikipedia, which are cool too.

**Comment by spencermountain** [comment]
(it's also wayy faster)

**Comment by MTKnife** [comment]
Sounds great!  I'll check it out when I get the chance.
