### ISSUE TITLE
pageid field

### ISSUE THREAD

**Issue by sbodenstein** [spencermountain/dumpster-dive#31]
Is there a way to include the pageid as a field in the resulting Mongo documents? This is very useful information to have and its annoying to have to add it via postprocessing.

**Comment by spencermountain** [comment]
Hey Sebastian! Yeah, this is definitely something we should add. We're currently rewriting a lot of this stuff in the dev branch, which is almost ready to release. Im currently on vacation, but plan to ship (and properly document) it in early april. 

If you'd like to include pageid before that, i think you can add a one liner [ here](https://github.com/spencermountain/wikipedia-to-mongodb/blob/master/src/page.js#L28) 

Cheers
https://github.com/spencermountain/wikipedia-to-mongodb/tree/dev

**Comment by sbodenstein** [comment]
Thanks so much! Looking forward to this new version :-)

**Comment by spencermountain** [comment]
hey @sbodenstein , 3.0.0 is out, have a play with it when you're free.
few errors on random pages, but otherwise will do the whole en-wiki in 6 or 7 hours.
lemme know how it goes

**Comment by sbodenstein** [comment]
Hi, sorry for the long absence! I've just tried out your new version and everything is looking good except for the `pageID` field: its an empty string for every article I've looked at (I'm using todays Wikipedia dump).

> are you using it at wolfram? that would be a life-goal of mine, completed.
We are using Wikipedia for machine learning, and this package is the cleanest parse of Wikipedia I've seen so far. Thank you so much for all of your efforts!

**Comment by sbodenstein** [comment]
Actually, getting another issue:
```
   -skipping page: ""
   -skipping page: ""
   -skipping page: ""
   -skipping page: ""
    worker #1  -  +1,000 pages  - (2.4s)  -  at 1,574,529
(node:2300) UnhandledPromiseRejectionWarning: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:588:16)
    at insertToDb (/usr/lib/node_modules/dumpster-dive/src/worker/index.js:43:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by spencermountain** [comment]
hey thanks Sebastian, have you updated to `3.1.0`? I'm getting pageIDs when I run that version, and that mongo-channel stuff seems sorted out. My boss was getting that before, but he got to the end of en-wiki with 3.1.0. Took about 7hrs.

Just a heads-up, some of the result format around templates and things will change in the next few releases, too. Things are moving at a pretty hot speed.

I'm happy to help get this working. I'm a huge fan of the stuff you guys are doing at wolfram.
Lemme know how 3.1.0 goes?

**Comment by sbodenstein** [comment]
> hey thanks Sebastian, have you updated to 3.1.0?

Ah, was using 3.0.4. Will update to 3.1.0 tomorrow and check again. Will definitely let you know how it goes!

> Just a heads-up, some of the result format around templates and things will change in the next few releases, too.

What sort of changes are being planned?

**Comment by sbodenstein** [comment]
@spencermountain: thanks, everything seems to be working fine with `3.1.0`!
