### ISSUE TITLE
Is the dev branch supposed to be working at all?

### ISSUE THREAD

**Issue by MTKnife** [spencermountain/dumpster-dive#34]
I just got a chance to try it, and I'm getting 0 pages for every batch....

**Comment by spencermountain** [comment]
hey Scott, yeah, if you run `npm i` and start mongo, you see some of the tests pass, and if you dl a simplewiki dump, `node scratch.js` will load it in

**Comment by MTKnife** [comment]
I ran the "npm install -g dumpster-dive" command, and I've got MongoDB running, and I'm trying to use the English _Wikipedia_ dump.  I don't have to add the "wikipedia" database manually, do I?

BTW, are you planning a way to specify how many cores to use?  It's running 8 "cores" on a 4-core/8-thread machine, which makes doing anything else hard.

**Comment by spencermountain** [comment]
oh, yeah that would be a good option to pass-in. I think it just uses the nodejs cpus command, which we should overwrite.
i may not be able to get to this today, did you try
`npm run test`?
cheers

**Comment by MTKnife** [comment]
Running `npm run test` is a Windows Bash shell (MINGW64 to be specific) gives me an error:

> > dumpster-dive@2.4.0 test C:\code\JavaScript\wikipedia-to-mongodb
> > "node_modules/.bin/tape" "./tests/*.test.js" | "node_modules/.bin/tap-spec" --color
> 
> 'node_modules' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! dumpster-dive@2.4.0 test: `"node_modules/.bin/tape" "./tests/*.test.js" | "node_modules/.bin/tap-spec" --color`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the dumpster-dive@2.4.0 test script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\sorr\AppData\Roaming\npm-cache\_logs\2018-04-11T15_42_02_144Z-debug.log

Something seems to be up with how it's parsing the path "node_modules/.bin/tape"--but in any case, I don't see "tape" (or "tap-spec") in that directory.

**Comment by spencermountain** [comment]
hey @MTKnife wanna check it out now? `3.0.0` it's on master.
cheers

**Comment by MTKnife** [comment]
I'm downloading the latest enwiki dump right now, to try it out.
