### ISSUE TITLE
TypeError: i.json is not a function

### ISSUE THREAD

**Issue by intrz** [spencermountain/dumpster-dive#48]
I'm just getting this error message when I try to run _dumpster ./enwiki-20180601-pages-articles.xml_

TypeError: i.json is not a function

TypeError: i.json is not a function
    at data.images.doc.images.map.i \dumpster-dive\node_modules\wtf_wikipedia\src\output\json\index.js:43:43

**Comment by spencermountain** [comment]
if you add a `console.log(page.title)` [here](https://github.com/spencermountain/dumpster-dive/blob/master/src/worker/02-parseWiki.js#L19) you should see which article is creating an invalid infobox
thanks.

**Comment by intrz** [comment]
It triggers on a lot of articles, maybe all articles.

Some examples:
"Gowanda Village Historic District"
"The Hanging Church"
"Edge of the City"
"Hampden Bridge (Kangaroo Valley)"
"Asura Buster: Eternal Warriors"

**Comment by spencermountain** [comment]
thanks @intrz I tried these and haven't seen any errors, en-wiki is running fine too, are you on the latest? `3.3.0`?

**Comment by intrz** [comment]
I'm on 3.4.0. Maybe I have an incompatible version of some dependency.

**Comment by carlock99** [comment]
i'm on 3.3.1 and i have the same problem. Have you find a solution for this problem?

**Comment by carlock99** [comment]
i have run the afwiki dump and in mongo i find only 23.209 pages and the output give a lot of error i.json

**Comment by spencermountain** [comment]
hi @carlock99 , can you try the latest, `v3.4.0`?

**Comment by carlock99** [comment]
same issue on the 3.4.0. I can't import the all wikipedia eng dump.

**Comment by mlmarenchino** [comment]
It happens to me when using the option "--images=true". To avoid it, you can use "--images=false". In fact, the problem is in line 43 of file "index.js" of "wtf_wikipedia":

```python
  if (options.images) {
    data.images = doc.images().map(i => i.json());
  }
```

**Comment by spencermountain** [comment]
hey thanks, I'll take a look at this tomorrow. sorry, thought I had got this one already.

**Comment by spencermountain** [comment]
hey, you guys wanna checkout `3.4.1`? think i got it

**Comment by carlock99** [comment]
Sure i will try it. with the —image=false option the old version  works well.

Inviato da iPhone

Il giorno 10 lug 2018, alle ore 21:55, spencer kelly <notifications@github.com<mailto:notifications@github.com>> ha scritto:


hey, you guys wanna checkout 3.4.1? think i got it

**Comment by mlmarenchino** [comment]
It works in version 3.4.1. Thanks!
