### ISSUE TITLE
cpu worker process same records multiple times

### ISSUE THREAD

**Issue by aymansalama** [spencermountain/dumpster-dive#63]
i noticed that my current run is progressing and the output is keep popping up. However the number of pages doesn't increase for like half an hour now. and keep giving duplicate warning. so i selected the page title that is stuck and grep it from the output of nohup and here is the results. Each line starts with a number that indicated the "line number" in nohup.out. It seems that the same page is processed by multiple core. You will notice the page "American wigeon" is processed multiple times from different cores. 

```
sudo grep -n 'American wigeon' nohup.out 
15517: #8  +100 pages  -  193ms - "American wigeon"
15519: #12  +0 pages  -  172ms - "American wigeon"
15538: #11  +0 pages  -  190ms - "American wigeon"
31954: #9  +0 pages  -  210ms - "American wigeon"
31958: #5  +0 pages  -  204ms - "American wigeon"
33109: #3  +0 pages  -  157ms - "American wigeon"
33121: #1  +0 pages  -  175ms - "American wigeon"
43075: #14  +0 pages  -  324ms - "American wigeon"
43077: #4  +0 pages  -  344ms - "American wigeon"
43093: #0  +0 pages  -  169ms - "American wigeon"
43247: #6  +0 pages  -  173ms - "American wigeon"
43253: #15  +0 pages  -  154ms - "American wigeon"
43257: #10  +0 pages  -  173ms - "American wigeon"
45677: #2  +0 pages  -  206ms - "American wigeon"
45693: #13  +0 pages  -  198ms - "American wigeon"
45719: #7  +0 pages  -  212ms - "American wigeon"
```

**Comment by spencermountain** [comment]
no, this is just logging the last record in the database. 
it certainly seems the script is going idle, or the workers are not dying when finished.
the "American wigeon" is only processed once though, gonna close this.

**Comment by aymansalama** [comment]
@spencermountain thank you so much for the explanations.  got it.
