### ISSUE TITLE
missing important pages in parsed results

### ISSUE THREAD

**Issue by xgeric** [spencermountain/dumpster-dive#66]
Salute all contributors to this amazing work!

I just finished parsing enwiki-20180901-pages-articles.xml. It seems to work properly with 5,081,528 records in Mongodb (which is as expected). However, when I query the DB (e.g. { "title": "London" }),  it seems that some important records are missed, e.g. London, China, India, etc. They should be contained in the original dump (as the index file indicates), but are somehow missed in the parsed DB. 

During the parsing, errors come out from time to time as shown in the screenshot, maybe related to the issue:
![image](https://user-images.githubusercontent.com/20608184/45925701-45ee5880-bee0-11e8-8a3a-00d07f24c4d0.png)

Just wondering if anyone had similar experience or may have any thoughts on possible causes?

Thanks! Once again, great work!

**Comment by aymansalama** [comment]
@xgeric can you please send me the procedure that you followed to get the 5M record. i failed horribly to get the data uploaded correctly. I am not sure if it is the procedure, commands, mongo version. 
here is my latest trial 
Database used 
mongod --fork --syslog --dbpath /data/mongo-3-6-trial4/
Command used 
nohup dumpster enwiki-latest-pages-articles.xml --html=true --images=false --batch_size 100 &
VERSION DUMPSTER-DIVE 3.6.1
on Google Cloud Engine, Debian. results was 1.1M articles only. Would you please help?

**Comment by xgeric** [comment]
> @xgeric can you please send me the procedure that you followed to get the 5M record. i failed horribly to get the data uploaded correctly. I am not sure if it is the procedure, commands, mongo version.
> here is my latest trial
> Database used
> mongod --fork --syslog --dbpath /data/mongo-3-6-trial4/
> Command used
> nohup dumpster enwiki-latest-pages-articles.xml --html=true --images=false --batch_size 100 &
> VERSION DUMPSTER-DIVE 3.6.1
> on Google Cloud Engine, Debian. results was 1.1M articles only. Would you please help?

Hi Ayman,

I am using Mongodb 2.6.10. on Linux Ubuntu.

Start DB: `mongod`
Start dumpster:
`dumpster enwiki-20180901-pages-articles.xml --citations=false --workers=10`

**Comment by aymansalama** [comment]
@xgeric thank man, i will try again. for some reason, i keep failing :(

**Comment by aymansalama** [comment]
@xgeric there is a behaviour that might answer your question. I used to set the batch_size to 100 to avoid 16mb problem in loading to mongodb. assuming that you didn't do that. So the batch_size is set to default at 1000. and typically, you will face the error of loading of 16mb. the important articles that you mentioned are the big ones that are full of data and possibly large in size. so it might be the reason. However don't load with batch_size set to 100 as it might not be successful as per my trials. i will let you know when the current task is finished. and lets see what @spencermountain has in his magic box.

**Comment by aymansalama** [comment]
@xgeric unfortunately even with the same procedure, i got around 2m articles


        closing down.



     -- final count is 2,357,382 pages --
       took 101.8 minutes

**Comment by xgeric** [comment]
> @xgeric there is a behaviour that might answer your question. I used to set the batch_size to 100 to avoid 16mb problem in loading to mongodb. assuming that you didn't do that. So the batch_size is set to default at 1000. and typically, you will face the error of loading of 16mb. the important articles that you mentioned are the big ones that are full of data and possibly large in size. so it might be the reason. However don't load with batch_size set to 100 as it might not be successful as per my trials. i will let you know when the current task is finished. and lets see what @spencermountain has in his magic box.

Man you are 100% right! Now I am able to parse the complete dump. Thanks a lot, and wish you can fix your problem soon.

**Comment by spencermountain** [comment]
hey thanks Xiaotao, what was your final number of articles?
I've never seen the `'connection closed'` error. Is there something this library could do to help prevent, or mitigate that?

**Comment by xgeric** [comment]
> hey thanks Xiaotao, what was your final number of articles?
> I've never seen the `'connection closed'` error. Is there something this library could do to help prevent, or mitigate that?

Hey Spencer,

The final number is 5,457,721 (this is achieved by merging 0901 and 0801 dumps but should not make much difference). 

The connection closed error seems to be caused by large batch_size (as @aymansalama points out). After setting the batch_size to 100 the error just went away. I think this is also the cause of the original page misses. I think it might be helpful to set the default batch_size parameter to a smaller number (e.g. 100).

I have to say I really enjoy the tool (fast speed, great GUI). Salute!

**Comment by spencermountain** [comment]
:champagne:
