### ISSUE TITLE
Pages not imported

### ISSUE THREAD

**Issue by andreasbergqvist** [spencermountain/dumpster-dive#82]
Hi
I tested to download the latest en wiki pages.
(https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2)

When I imported it only imported the id and title.

Tried to figure out why, and it seems like Wikipedia added an attribute to the <text> node.

It's now:
`<text bytes="80055" xml:space="preserve">`

Your code does not seem to handle the bytes attribute.

I tested adding it and it seems to work now.

Thought about sending a pull request, but was a little bit unsure about:
[https://github.com/spencermountain/dumpster-dive/blob/master/src/worker/01-parsePage.js#L41](https://github.com/spencermountain/dumpster-dive/blob/master/src/worker/01-parsePage.js#L41)

Maybe the `<text>` regexp should be even more "open" to any kind of attributes?

Example:
`<text[^>]*>([\s\S]*?)<\/text>`

**Comment by spencermountain** [comment]
hey Andreas, sorry for the delay.
ah! of course, pr is welcome!
thank you for finding this.

**Comment by spencermountain** [comment]
i should try to writtle less-crappy regex, in the future.

**Comment by SimonBurfield** [comment]
Has this been fixed?

**Comment by spencermountain** [comment]
just gonna release wtf_wikipedia 8.2 then will update this lib.
Will be today or tomorrow.
cheers

**Comment by SimonBurfield** [comment]
You are a great man!

**Comment by spencermountain** [comment]
fixed in `5.3.0`
cheers
