### ISSUE TITLE
--plaintext not working

### ISSUE THREAD

**Issue by SimonBurfield** [spencermountain/dumpster-dive#83]
Hi there, been a big fan of this, ever since it was called wp2mongo 

I am sure that --plaintext=true used to give me the plaintext of the page.

I run it now (with an older Wiki download as the current format doesn't work as per other bugs)

I get Id, title, categories, sections, pageId ? what have I missed?

**Comment by SimonBurfield** [comment]
I got around this by writing a node script and not doing it via command line

**Comment by spencermountain** [comment]
ah, fixed in `5.3.0`. thanks for the heads-up.
