### ISSUE TITLE
Secured Database URL is not accepted

### ISSUE THREAD

**Issue by vyank** [spencermountain/dumpster-dive#88]
This utility does the work very well, but just one issue is that it is hardcoded the url for mongodb. Can it be parameterised?

**Comment by spencermountain** [comment]
sure, i'd be happy to support that.
is it [this one](https://github.com/spencermountain/dumpster-dive/blob/master/src/lib/open-db.js#L9)?
cheers

**Comment by vyank** [comment]
Yes that is correct, great. Thank you.

**Comment by spencermountain** [comment]
hey @vyank i've added support for `{ db_url: 'mongodb://localhost:27017/' }` in `5.4.0`.
good idea, thank you

**Comment by vyank** [comment]
Thank you @spencermountain . Appreciate it.
