### ISSUE TITLE
Update wtf_wikipedia and allow wtf.extend()

### ISSUE THREAD

**Issue by andremacola** [spencermountain/dumpster-dive#97]
The wtf_wikipedia latest version is `9.0.1` and is it possible to import wtf extensions with wtf.extend()? Tried without success.

**Comment by spencermountain** [comment]
sure, good idea. I can do this hopefully today.
cheers

**Comment by spencermountain** [comment]
hey @andremacola i've updated wtf and released it as 5.6.0
please let me know if you see any issues
thanks
